---
- name: Creating Redis backup folder.
  file:
    dest: "{{ redis_path }}/{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "backup", owner: "root", mode: "0755" }
    - { path: "backup/redis", owner: "redis", mode: "0750" }

- name: Creating Rclone configureation folder.
  file:
    dest: "/etc/rclone"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - redis_backupset_arg.cloud_rsync | bool
    - redis_backupset_arg.cloud_drive is defined

- name: Rclone configuration file transfer.
  template:
    src: "rclone.conf.j2"
    dest: "/etc/rclone/redis.conf"
    owner: "redis"
    group: "redis"
    mode: "0640"
  when:
    - redis_backupset_arg.cloud_rsync | bool
    - redis_backupset_arg.cloud_drive is defined

- name: Redis Backup Scripts file transfer.
  template:
    src: "redis_hot_backup.sh.j2"
    dest: "/usr/local/bin/redis_hot_backup.sh"
    owner: "redis"
    group: "redis"
    mode: "0660"
  no_log: true

- name: Create Redis backup job.
  cron:
    user: "redis"
    name: "Redis Hot Backup"
    minute: "{{ ( ansible_hostname | hash | list | map('int',0,16) | sum ) % 60 }}"
    hour: "{{ (( ansible_hostname | hash | list | map('int',0,16) | sum ) % 2) + 1 }}"
    job: "/bin/sh /usr/local/bin/redis_hot_backup.sh"
