---
- name: Add prometheus redis_exporter YUM repositories
  yum_repository:
    name: '{{ redis_exporter_repo_name }}'
    description: '{{ redis_exporter_repo_name }} YUM repository'
    file: '{{ redis_exporter_repo_name }}'
    baseurl: '{{ redis_exporter_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the prometheus redis_exporter
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ redis_exporter_packages }}'
  register: soft_update

- name: Prometheus redis_exporter configure file transfer
  template:
    src: 'redis_exporter'
    dest: '/etc/default/'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: conf_update

- name: Ensure prometheus redis_exporter service is enabled
  systemd:
    name: 'redis_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when:
    - soft_update is changed or conf_update is changed