---
- name: Add prometheus redis_exporter YUM repositories
  yum_repository:
    name: '{{ redis_exporter_repo_name }}'
    description: '{{ redis_exporter_repo_name }} YUM repository'
    file: '{{ redis_exporter_repo_name }}'
    baseurl: '{{ redis_exporter_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the prometheus redis_exporter
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ redis_exporter_packages }}'
  register: soft_update
  until: soft_update is succeeded
  retries: 5
  delay: 2

- name: Prometheus redis_exporter configure file transfer
  template:
    src: 'redis_exporter'
    dest: '/etc/default/'
    backup: 'yes'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  register: conf_update
  no_log: true

- name: Ensure prometheus redis_exporter service is enabled
  systemd:
    name: 'redis_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when: soft_update is changed or conf_update is changed

- name: Redis Sentinel exporter program binary transfer.
  unarchive:
    src: 'redis_sentinel_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: redis_sentinel_exporter_update
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length > 2

- name: Redis Sentinel exporter configure file transfer.
  template:
    src: 'redis_sentinel_exporter.default.j2'
    dest: '/etc/default/redis_sentinel_exporter'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  register: redis_sentinel_exporter_config
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length > 2

- name: Redis Sentinel service file transfer.
  copy:
    src: 'redis_sentinel_exporter.service'
    dest: '/lib/systemd/system'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: redis_sentinel_systemd_update
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length > 2

- name: Reloading the Redis Sentinel exporter service.
  systemd:
    name: 'redis_sentinel_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length > 2
    - redis_sentinel_exporter_update is changed or redis_sentinel_exporter_config is changed or redis_sentinel_systemd_update is changed
