---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Ensure Redis firewall port is allow
  firewalld:
    port: '{{ item }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop:
    - '{{ redis_port }}'
    - '{{ redis_exporter_port }}'
  when: services_state.ansible_facts.services["firewalld.service"].state == 'running'