---
- name: Gather Redis node variables for cluster.
  set_fact:
    redis_servers: "\
      {% set _redis_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
      {% if redis_cluster_name is defined %}\
      {% set _redis_cluster_name = redis_cluster_name | default('') %}\
      {% if ( _redis_cluster_name == redis_cluster_name ) %}\
      {% if _redis_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
      {% endif %}\
      {% endif %}\
      {% endfor %}\
      {{ _redis_servers }}"
  when: redis_cluster_mode != 'standalone'

- name: Include tasks for specific OS.
  include: "{{ ansible_distribution_file_variety }}.yml"

- name: Include firewall tasks.
  include: "firewall.yml"

- name: Straight to getenforce selinux status.
  include: "selinux.yml"

- name: Include certificate tasks.
  include: "certificates.yml"
  when:
    - redis_ssl | bool
    - redis_authorization | bool
    - redis_version.split('.')[0] | int > 5

- name: Configuration the Redis.
  include: "configureation.yml"

- name: Include backup tasks.
  include: "backup.yml"

- name: Include prometheus exporter tasks
  include: "exporter.yml"
  when: exporter_is_install | bool

- name: Flush handlers.
  meta: flush_handlers

- name: Registered with HashiCorp Consul.
  include: "register.yml"
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include cluster tasks.
  include: "cluster.yml"
  when:
    - redis_servers[0] in ansible_default_ipv4.address
    - redis_cluster_mode == 'cluster'
    - redis_servers | length == 6
