---
- name: Gather Redis node variables for cluster.
  set_fact:
    redis_servers: "\
      {% set _redis_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
        {% if redis_cluster_name is defined %}\
          {% set _redis_cluster_name = redis_cluster_name | default('') %}\
          {% if ( _redis_cluster_name == redis_cluster_name ) %}\
            {% if _redis_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
          {% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _redis_servers }}"
  when: redis_cluster_mode != 'standalone'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Include certificate tasks
  include: 'certificates.yml'
  when:
    - redis_ssl | bool
    - redis_authorization | bool
    - redis_version.split('.')[0] | int > 5

- name: Configuration the Redis
  include: 'configureation.yml'

- name: Reload the Redis configuration
  systemd:
    name: 'redis.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when:
    - conf_update is changed or comm_update is changed
    - ansible_distribution_major_version|int > 6

- name: Reload the Redis Sentinels configuration
  systemd:
    name: 'redis-sentinel.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length > 2
    - sentinel_conf_update is changed or sentinel_monitor_conf_update is changed
    - ansible_distribution_major_version|int > 6

- name: Include backup tasks
  include: 'backup.yml'

- name: Include prometheus exporter tasks
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
