---
- name: Gather Redis node variables for cluster.
  set_fact:
    redis_servers: "\
      {% set _redis_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
      {% if redis_cluster_name is defined %}\
      {% set _redis_cluster_name = redis_cluster_name | default('') %}\
      {% if ( _redis_cluster_name == redis_cluster_name ) %}\
      {% if _redis_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
      {% endif %}\
      {% endif %}\
      {% endfor %}\
      {{ _redis_servers }}"
  when: redis_cluster_mode != 'standalone'

- name: Include tasks for specific OS.
  include: "{{ ansible_distribution_file_variety }}.yml"

- name: Include firewall tasks.
  include: "firewall.yml"

- name: Straight to getenforce selinux status.
  include: "selinux.yml"

- name: Include certificate tasks.
  include: "certificates.yml"
  when:
    - redis_ssl | bool
    - redis_authorization | bool
    - redis_version.split('.')[0] | int > 5

- name: Configuration the Redis.
  include: "configureation.yml"

- name: Include sentinel tasks.
  include: "sentinel.yml"
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length >= 3

- name: Include backup tasks.
  include: "backup.yml"

- name: Include prometheus exporter tasks.
  include: "exporter.yml"
  when: exporter_is_install | bool

- name: Flush handlers.
  meta: flush_handlers

- name: Registered with HashiCorp Consul.
  include: "register.yml"
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include cluster tasks.
  include: "cluster.yml"
  when:
    - redis_cluster_mode == 'cluster'
    - redis_servers[0] in ansible_default_ipv4.address
    - redis_servers | length == 6

- name: Cluster Members check.
  debug:
    msg:
      - "The minimal cluster that works as expected must contain at least three master nodes,"
      - "We strongly recommend a six-node cluster, with three masters and three replicas,"
      - "Now is {{ redis_servers | length }},"
      - "Task skipped completely."
      - "集群必须至少包含三个主节点，"
      - "强烈建议使用六节点集群，包括三个主节点和三个副本，"
      - "实际节点数量为 {{ redis_servers | length }}，"
      - "任务已跳过。"
  when:
    - redis_cluster_mode == 'cluster'
    - redis_servers | length != 6
  run_once: true

- name: Sentinel Members check.
  debug:
    msg:
      - "You need at least three Sentinel instances for a robust deployment,"
      - "Now is {{ redis_servers | length }},"
      - "Task skipped completely."
      - "可靠的部署至少需要三个哨兵实例，"
      - "实际节点数量为 {{ redis_servers | length }}，"
      - "任务已跳过。"
  when:
    - redis_cluster_mode == 'sentinel'
    - redis_servers | length < 3
  run_once: true
