---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install the Redis dependencies packages
  yum:
    name: '{{ redis_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_update
  until: soft_update is succeeded
  retries: 5
  delay: 2

- name: Install the Redis packages
  yum:
    name: 'http://rpms.remirepo.net/store/redis/{{ redis_version }}/redis-{{ redis_version }}-1.el{{ ansible_distribution_major_version }}.remi.{{ ansible_architecture }}.rpm'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_update
  until: soft_update is succeeded
  retries: 5
  delay: 2

- name: Changing Limits for Redis services
  lineinfile:
    state: 'present'
    dest: '/etc/systemd/system/redis.service.d/limit.conf'
    insertafter: '^\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^LimitMEMLOCK=', line: 'LimitMEMLOCK=infinity' }
    - { regexp: '^LimitCORE=', line: 'LimitCORE=infinity' }
    - { regexp: '^LimitNPROC=', line: 'LimitNPROC={{ redis_ulimit_nproc }}' }
    - { regexp: '^LimitNOFILE=', line: 'LimitNOFILE={{ redis_ulimit_nofile }}' }
  register: systemd_update
