---
- name: Add redis_exporter YUM repositories
  yum_repository:
    name: '{{ redis_exporter_repo_name }}'
    description: '{{ redis_exporter_repo_name }} YUM repository'
    file: '{{ redis_exporter_repo_name }}'
    baseurl: '{{ redis_exporter_repo_url }}'
    gpgcheck: no

- name: Install the redis_exporter packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ redis_exporter_packages }}'
  register: soft_update

- name: redis_exporter configure file transfer
  copy:
    src: 'redis_exporter'
    dest: '/etc/default/'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: conf_update

- name: redis_exporter service is enabled
  systemd:
    name: 'redis_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: yes
  when:
    - soft_update.changed or conf_update.changed

- name: Ensure Prometheus firewall port is allow
  firewalld:
    port: '{{ redis_exporter_port }}'
    permanent: 'true'
    state: 'enabled'
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int > 6
  register: result

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when:
    - result.changed
