---
- name: Add prometheus redis_exporter YUM repositories
  yum_repository:
    name: '{{ redis_exporter_repo_name }}'
    description: '{{ redis_exporter_repo_name }} YUM repository'
    file: '{{ redis_exporter_repo_name }}'
    baseurl: '{{ redis_exporter_repo_url }}'
    gpgcheck: no

- name: Install the prometheus redis_exporter
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ redis_exporter_packages }}'
  register: soft_update

- name: Prometheus redis_exporter configure file transfer
  copy:
    src: 'redis_exporter'
    dest: '/etc/default/'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: conf_update

- name: Ensure prometheus redis_exporter service is enabled
  systemd:
    name: 'redis_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: yes
  when:
    - soft_update.changed or conf_update.changed

- name: Ensure Prometheus firewall port is allow
  firewalld:
    port: '{{ redis_exporter_port }}/tcp'
    permanent: 'true'
    state: 'enabled'
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int > 6
  register: result

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when:
    - result.changed

- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_http_port }}/v1/agent/service/register'
    method: 'PUT'
    headers:
      X-Consul-Token: "{{ consul_exporter_token }}"
    body: '{"ID":"{{ inventory_hostname | upper }}_redis_exporter","name":"redis_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ redis_exporter_port }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ redis_exporter_port }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"5s"}]}'
    body_format: 'json'
  environment:
    no_proxy: '{{ item }}'
  with_items: '{{ consul_clients }}'
  when: consul_is_register
  no_log: true
