- name: Restart the Redis service.
  systemd:
    name: "redis.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"

- name: Restart the Redis Sentinels service.
  systemd:
    name: "redis-sentinel.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"

- name: Restart the Redis exporter service.
  systemd:
    name: "redis_exporter.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"

- name: Restart the Redis sentinel exporter service.
  systemd:
    name: "redis_sentinel_exporter.service"
    enabled: "yes"
    state: "restarted"
    daemon_reload: "yes"